# This CASA pipescript is meant for use with CASA 6.6.1 and pipeline 2024.1.0.8
context = h_init()
context.set_state('ProjectSummary', 'observatory', 'Karl G. Jansky Very Large Array')
context.set_state('ProjectSummary', 'telescope', 'EVLA')
try:
    hifv_importdata(vis=['24A-411.sb45153015.eb45227399.60343.435757858795.ms'])
    hifv_flagdata(hm_tbuff='1.5int', fracspw=0.01, intents='*POINTING*,*FOCUS*,*ATMOSPHERE*,*SIDEBAND_RATIO*, *UNKNOWN*, *SYSTEM_CONFIGURATION*, *UNSPECIFIED#UNSPECIFIED*')
    hifv_vlasetjy()
    hifv_priorcals(show_tec_maps=False)
    hifv_aoflagger(flag_target='0', aoflagger_file='calibrator.lua')
    hifv_aoflagger(flag_target='1', aoflagger_file='calibrator.lua')
    hifv_aoflagger(flag_target='3', aoflagger_file='calibrator.lua')
    hifv_aoflagger(flag_target='5', aoflagger_file='calibrator.lua')
    hifv_testBPdcals()
    hifv_semiFinalBPdcals()
    hifv_solint()
    hifv_fluxboot()
    hifv_finalcals()
    hifv_applycals()
    hifv_aoflagger(flag_target='2', aoflagger_file='science.lua')
    hifv_aoflagger(flag_target='4', aoflagger_file='science.lua')
    hifv_aoflagger(flag_target='6', aoflagger_file='science.lua')
    hifv_statwt()
    hifv_plotsummary()
    hifv_exportdata()
finally:
    h_save()

