# This CASA pipescript is meant for use with CASA 6.6.1 and pipeline 2024.1.0.8
context = h_init()
context.set_state('ProjectSummary', 'observatory', 'Karl G. Jansky Very Large Array')
context.set_state('ProjectSummary', 'telescope', 'EVLA')
try:
    hifv_importdata(vis=['25A-157.sb47894733.eb48078570.60733.28727417824.ms'])
    hifv_flagdata(hm_tbuff='1.5int', fracspw=0.01, intents='*POINTING*,*FOCUS*,*ATMOSPHERE*,*SIDEBAND_RATIO*, *UNKNOWN*, *SYSTEM_CONFIGURATION*, *UNSPECIFIED#UNSPECIFIED*')
    hifv_vlasetjy()
    hifv_priorcals(show_tec_maps=False)
    hifv_aoflagger(flag_target='0', aoflagger_file='1331+305=3C286.lua')
    hifv_testBPdcals()
    hifv_semiFinalBPdcals()
    hifv_aoflagger(flag_target='1', aoflagger_file='J1041+0610.lua', use_corrected=True)
    hifv_aoflagger(flag_target='3', aoflagger_file='J1058+0133.lua', use_corrected=True)
    hifv_solint()
    hifv_fluxboot()
    hifv_aoflagger(flag_target='1', aoflagger_file='microwave-cleanup.lua', use_corrected=True)
    hifv_aoflagger(flag_target='3', aoflagger_file='microwave-cleanup.lua', use_corrected=True)
    hifv_finalcals()
    hifv_applycals()
    hifv_aoflagger(flag_target='2', aoflagger_file='Z3146.lua', use_corrected=True)
    hifv_aoflagger(flag_target='4', aoflagger_file='RXCJ1115+0129.lua', use_corrected=True)
    hifv_statwt()
    hifv_plotsummary()
    hifv_exportdata()
finally:
    h_save()

