# This CASA pipescript is meant for use with CASA 6.6.1 and pipeline 2024.1.0.8
context = h_init()
context.set_state('ProjectSummary', 'observatory', 'Karl G. Jansky Very Large Array')
context.set_state('ProjectSummary', 'telescope', 'EVLA')
try:
    hifv_importdata(vis=['25A-157.sb47896788.eb48078564.60733.06076180555.ms'])
    hifv_flagdata(hm_tbuff='1.5int', fracspw=0.01, intents='*POINTING*,*FOCUS*,*ATMOSPHERE*,*SIDEBAND_RATIO*, *UNKNOWN*, *SYSTEM_CONFIGURATION*, *UNSPECIFIED#UNSPECIFIED*')
    hifv_vlasetjy()
    hifv_priorcals(show_tec_maps=False)
    hifv_aoflagger(flag_target='"0137+331=3C48"', aoflagger_file='0137+331=3C48.lua')
    hifv_testBPdcals()
    hifv_semiFinalBPdcals()
    hifv_aoflagger(flag_target='J0424+0204', aoflagger_file='J0424+0204.lua')
    hifv_solint()
    hifv_fluxboot()
    hifv_aoflagger(flag_target='J0424+0204', aoflagger_file='J0424+0204-corrected.lua')
    hifv_finalcals()
    hifv_applycals()
    hifv_aoflagger(flag_target='A478', aoflagger_file='A478.lua', use_corrected=True)
    hifv_statwt()
    hifv_plotsummary()
    hifv_exportdata()
finally:
    h_save()

